#!/usr/bin/env python
# coding: utf-8

# In[1]:


graph = {
    '1': ['2', '6', '8'],
    '2': ['1', '3'],
    '3': ['2', '4', '9'],
    '4': ['3', '5'],
    '5': ['4', '7', '9'],
    '6': ['1', '7', '8'],
    '7': ['5', '6', '9'],
    '8': ['1', '6'],
    '9': ['3', '5', '7']
}

visit = []
stack = []

def dfs(visit, graph, node, goal):
    visit.append(node)
    stack.append(node)
   
    while stack:
        s = stack.pop()
        print(s, end=" ")
        if s == goal:
            break
        else:
            for neigh in graph[s]:
                if neigh not in visit:
                    visit.append(neigh)
                    stack.append(neigh)

t = input("Enter goal: ")
dfs(visit, graph, '1', t)


# ![PPkbNoMVsuqTMxap.png](attachment:PPkbNoMVsuqTMxap.png)

# In[ ]:



